function s = dot(TH1, TH2)
%DOT 

% Check if the base points are the same
if ~isequal(base_point(TH1), base_point(TH2))
    error('The vectors belong to different tangent spaces')
end

s = 0;

% Sum stuff at this level
s = s + dot(TH1.TD(:), TH2.TD(:)) + ... 
    dot(TH1.TU(:), TH2.TU(:)) + ...
    dot(TH1.TV(:), TH2.TV(:)) + ...
    dot(TH1.PU(:), TH2.PU(:)) + ...
    dot(TH1.PV(:), TH2.PV(:)) + ...    
    dot(TH1.TR(:), TH2.TR(:)) + ...
    dot(TH1.TW(:), TH2.TW(:)) + ...
    dot(TH1.PR(:), TH2.PR(:)) + ...
    dot(TH1.PW(:), TH2.PW(:)) + ...
    dot(TH1.TB12(:), TH2.TB12(:)) + ...
    dot(TH1.TB21(:), TH2.TB21(:));

if ~TH1.leafnode
    s = s + dot(TH1.TA11, TH2.TA11) + dot(TH1.TA22, TH2.TA22);
end


end

